# Generated by Django 3.2.8 on 2021-10-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy_product',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='allergy_product',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='Allergy_Product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
